version: '3'

services:
  mongodb:
      image: mongo:5.0.27
      container_name: api-cars-mongodb
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin_password
        MONGO_INITDB_DATABASE: cars_api
      volumes:
        - "./data/db:/data/db"