const Car = require("../models/Car.model");

async function seedCarsFn(req, res) {
   try {
      const carsData = [
         {
            model: "BMW iX",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "87350",
         },
         {
            model: "BMW iX M60",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            price: "140600",
         },
         {
            model: "BMW i7",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "115700",
            isNew: true,
         },
         {
            model: "BMW i7 M70 xDrive",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            price: "186650",
            isNew: true,
         },
         {
            model: "BMW i5 Touring",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "79550",
            isNew: true,
         },
         {
            model: "BMW i5 M60 xDrive Touring",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            price: "117050",
            isNew: true,
         },
         {
            model: "BMW i5 Berlina",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "76950",
            isNew: true,
         },
         {
            model: "BMW i5 M60 xDrive Berlina",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            price: "114450",
            isNew: true,
         },
         {
            model: "Nuevo BMW i4",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "58600",
            isNew: true,
         },
         {
            model: "Nuevo BMW i4 M50",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            isNew: true,
         },
         {
            model: "BMW iX3",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "74600",
         },
         {
            model: "BMW iX2",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "58200",
            isNew: true,
         },
         {
            model: "BMW iX1",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "49100",
         },
         {
            model: "BMW XM",
            type: "BMW M",
            fuelType: "HÍBRIDO ENCHUFABLE",
            price: "201700",
            isNew: true,
         },
         {
            model: "BMW X7",
            type: "series X",
            fuelType: "GASOLINA",
            price: "115800",
         },
         {
            model: "BMW X7 M60i",
            type: "BMW M",
            fuelType: "GASOLINA",
            price: "146500",
         },
         {
            model: "BMW X6",
            type: "BMW X",
            fuelType: "GASOLINA•DIÉSEL",
            price: "99300",
         },
         {
            model: "BMW X6 M",
            type: "BMW M",
            fuelType: "GASOLINA",
            price: "180750",
         },
         {
            model: "BMW X5",
            type: "BMW X",
            fuelType: "GASOLINA•DIÉSEL•HÍBRIDO ENCHUFABLE",
            price: "102650",
         },
         {
            model: "BMW X5 M",
            type: "BMW M",
            fuelType: "GASOLINA",
            price: "177250",
         },
         {
            model: "BMW X4",
            type: "BMW X",
            fuelType: "GASOLINA•DIÉSEL",
            price: "60600",
         },
         {
            model: "BMW X4 M",
            type: "BMW M",
            fuelType: "GASOLINA•DIÉSEL",
            price: "121750",
         },
         {
            model: "BMW X3",
            type: "BMW X",
            fuelType: "GASOLINA•DIÉSEL",
            price: "55500",
         },
         {
            model: "BMW X3 M",
            type: "BMW M",
            fuelType: "GASOLINA•DIÉSEL",
            price: "119600",
         },
         {
            model: "BMW X2",
            type: "series X",
            fuelType: "GASOLINA•DIÉSEL",
            price: "47300",
            isNew: true,
         },
         {
            model: "BMW X2 M35i xDrive",
            type: "BMW M",
            fuelType: "GASOLINA",
            price: "72000",
            isNew: true,
         },
         {
            model: "BMW X1",
            type: "series X",
            fuelType: "GASOLINA•DIÉSEL•HÍBRIDO ENCHUFABLE",
            price: "55250",
         },
         {
            model: "BMW X1 M35i xDrive",
            type: "BMW M",
            fuelType: "GASOLINA",
            price: "70450",
            isNew: true,
         },
         {
            model: "BMW iX",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "87150",
         },
         {
            model: "BMW iX M60",
            type: "BMW M",
            fuelType: "ELÉCTRICO",
            price: "140600",
         },
         {
            model: "BMW iX3",
            type: "BMW i",
            fuelType: "ELÉCTRICO",
            price: "74600",
         },
      ];

      //   const carsData = [
      //      {
      //         name: "Carro 1",
      //         price: 20000,
      //         image: "url_imagen_1",
      //         year: 2020,
      //         description: "Descripción del carro 1",
      //         category: "sedan",
      //         brand: "Marca 1",
      //         kilometers: 50000,
      //      },
      //      {
      //         name: "Carro 2",
      //         price: 15000,
      //         image: "url_imagen_2",
      //         year: 2018,
      //         description: "Descripción del carro 2",
      //         category: "hatchback",
      //         brand: "Marca 2",
      //         kilometers: 60000,
      //      },
      //      // Agregar más ejemplos de carros aquí
      //      {
      //         name: "Carro 3",
      //         price: 25000,
      //         image: "url_imagen_3",
      //         year: 2019,
      //         description: "Descripción del carro 3",
      //         category: "SUV",
      //         brand: "Marca 3",
      //         kilometers: 30000,
      //      },
      //      {
      //         name: "Carro 4",
      //         price: 18000,
      //         image: "url_imagen_4",
      //         year: 2017,
      //         description: "Descripción del carro 4",
      //         category: "sedan",
      //         brand: "Marca 4",
      //         kilometers: 70000,
      //      },
      //      {
      //         name: "Carro 5",
      //         price: 30000,
      //         image: "url_imagen_5",
      //         year: 2021,
      //         description: "Descripción del carro 5",
      //         category: "hatchback",
      //         brand: "Marca 5",
      //         kilometers: 20000,
      //      },
      //      {
      //         name: "Carro 6",
      //         price: 22000,
      //         image: "url_imagen_6",
      //         year: 2018,
      //         description: "Descripción del carro 6",
      //         category: "SUV",
      //         brand: "Marca 6",
      //         kilometers: 40000,
      //      },
      //      {
      //         name: "Carro 7",
      //         price: 19000,
      //         image: "url_imagen_7",
      //         year: 2020,
      //         description: "Descripción del carro 7",
      //         category: "sedan",
      //         brand: "Marca 7",
      //         kilometers: 60000,
      //      },
      //      {
      //         name: "Carro 8",
      //         price: 28000,
      //         image: "url_imagen_8",
      //         year: 2019,
      //         description: "Descripción del carro 8",
      //         category: "hatchback",
      //         brand: "Marca 8",
      //         kilometers: 35000,
      //      },
      //      {
      //         name: "Carro 9",
      //         price: 21000,
      //         image: "url_imagen_9",
      //         year: 2018,
      //         description: "Descripción del carro 9",
      //         category: "SUV",
      //         brand: "Marca 9",
      //         kilometers: 50000,
      //      },
      //      {
      //         name: "Carro 10",
      //         price: 32000,
      //         image: "url_imagen_10",
      //         year: 2022,
      //         description: "Descripción del carro 10",
      //         category: "sedan",
      //         brand: "Marca 10",
      //         kilometers: 10000,
      //      },
      //   ];

      await Car.deleteMany();
      const createdCars = await Car.create(carsData);
      console.log("Datos de ejemplo de autos creados con éxito:", createdCars);
      return res.json({ ok: true });
   } catch (error) {
      console.error("Error al sembrar datos de ejemplo:", error);
   }
}

module.exports = { seedCarsFn };
