const carsDataSeed = [
   {
      model: "BMW iX",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "87350",
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX M60",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "140600",
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i7",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "115700",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i7 M70 xDrive",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "186650",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 Touring",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "79550",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 M60 xDrive Touring",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "117050",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 Berlina",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "76950",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 M60 xDrive Berlina",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "114450",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "Nuevo BMW i4",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "58600",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "Nuevo BMW i4 M50",
      type: "BMW M",
      fuelType: "ELECTRICO",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX3",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "74600",
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX2",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "58200",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX1",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "49100",
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW XM",
      type: "BMW M",
      fuelType: "HIBRIDO ENCHUFABLE",
      price: "201700",
      isNew: true,
      stock: 2123,
      image: "/ix.webp",
      sales: 33,
   },
   // ,
   // {
   //    model: "BMW X7",
   //    type: "series X",
   //    fuelType: "GASOLINA",
   //    price: "115800",
   // },
   // {
   //    model: "BMW X7 M60i",
   //    type: "BMW M",
   //    fuelType: "GASOLINA",
   //    price: "146500",
   // },
   // {
   //    model: "BMW X6",
   //    type: "BMW X",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "99300",
   // },
   // {
   //    model: "BMW X6 M",
   //    type: "BMW M",
   //    fuelType: "GASOLINA",
   //    price: "180750",
   // },
   // {
   //    model: "BMW X5",
   //    type: "BMW X",
   //    fuelType: "GASOLINA•DIESEL•HIBRIDO ENCHUFABLE",
   //    price: "102650",
   // },
   // {
   //    model: "BMW X5 M",
   //    type: "BMW M",
   //    fuelType: "GASOLINA",
   //    price: "177250",
   // },
   // {
   //    model: "BMW X4",
   //    type: "BMW X",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "60600",
   // },
   // {
   //    model: "BMW X4 M",
   //    type: "BMW M",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "121750",
   // },
   // {
   //    model: "BMW X3",
   //    type: "BMW X",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "55500",
   // },
   // {
   //    model: "BMW X3 M",
   //    type: "BMW M",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "119600",
   // },
   // {
   //    model: "BMW X2",
   //    type: "series X",
   //    fuelType: "GASOLINA•DIESEL",
   //    price: "47300",
   //    isNew: true,
   // },
   // {
   //    model: "BMW X2 M35i xDrive",
   //    type: "BMW M",
   //    fuelType: "GASOLINA",
   //    price: "72000",
   //    isNew: true,
   // },
   // {
   //    model: "BMW X1",
   //    type: "series X",
   //    fuelType: "GASOLINA•DIESEL•HIBRIDO ENCHUFABLE",
   //    price: "55250",
   // },
   // {
   //    model: "BMW X1 M35i xDrive",
   //    type: "BMW M",
   //    fuelType: "GASOLINA",
   //    price: "70450",
   //    isNew: true,
   // },
   // {
   //    model: "BMW iX",
   //    type: "BMW i",
   //    fuelType: "ELECTRICO",
   //    price: "87150",
   // },
   // {
   //    model: "BMW iX M60",
   //    type: "BMW M",
   //    fuelType: "ELECTRICO",
   //    price: "140600",
   // },
   // {
   //    model: "BMW iX3",
   //    type: "BMW i",
   //    fuelType: "ELECTRICO",
   //    price: "74600",
   // },
];

module.exports = { carsDataSeed };
