const carsDataSeed = [
   {
      model: "BMW iX",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "87350",
      stock: 21,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX M60",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "140600",
      stock: 40,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i7",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "115700",
      isNew: true,
      stock: 5,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i7 M70 xDrive",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "186650",
      isNew: true,
      stock: 10,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 Touring",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "79550",
      isNew: true,
      stock: 50,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 M60 xDrive Touring",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "117050",
      isNew: true,
      stock: 22,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 Berlina",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "76950",
      isNew: true,
      stock: 8,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW i5 M60 xDrive Berlina",
      type: "BMW M",
      fuelType: "ELECTRICO",
      price: "114450",
      isNew: true,
      stock: 0,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "Nuevo BMW i4",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "58600",
      isNew: true,
      stock: 44,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "Nuevo BMW i4 M50",
      type: "BMW M",
      fuelType: "ELECTRICO",
      isNew: true,
      stock: 89,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX3",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "74600",
      stock: 76,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX2",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "58200",
      isNew: true,
      stock: 70,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW iX1",
      type: "BMW i",
      fuelType: "ELECTRICO",
      price: "49100",
      stock: 40,
      image: "/ix.webp",
      sales: 33,
   },
   {
      model: "BMW XM",
      type: "BMW M",
      fuelType: "HIBRIDO ENCHUFABLE",
      price: "201700",
      isNew: true,
      stock: 5,
      image: "/ix.webp",
      sales: 33,
   },
];

module.exports = { carsDataSeed };
